[alembic]
script_location = app/db/migrations
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic
handlers =
qualname = alembic

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = INFO
handlers =

