name: Build Windows EXE (Launcher)

on:
  workflow_dispatch:

jobs:
  build_launcher_exe:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build project
        run: |
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            dotnet restore $_.FullName
            dotnet publish $_.FullName -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher-exe
          path: '**/publish/'
