name: Build Windows EXE (Launcher)

on:
  workflow_dispatch:

jobs:
  build_launcher_exe:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish EXE
        run: |
          Set-Location ${{ github.workspace }}
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Publishing $($_.FullName)"
            dotnet restore $_.FullName
            dotnet publish $_.FullName -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
          }

      - name: Debug EXEs
        run: |
          Set-Location ${{ github.workspace }}
          Write-Host "Checking for EXEs..."
          Get-ChildItem -Recurse -Filter *.exe | ForEach-Object { Write-Host $_.FullName }

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: launcher-exe
          path: 'apps/launcher-dotnet/bin/Release/net8.0/win-x64/publish/*.exe'
